from distutils.core import setup

setup(
    name='SafeNetworkingProject',
    version='v1dev',
    packages=['', 'lib.python2.7.distutils', 'lib.python2.7.encodings', 'lib.python2.7.site-packages.pip',
              'lib.python2.7.site-packages.pip.req', 'lib.python2.7.site-packages.pip.vcs',
              'lib.python2.7.site-packages.pip.utils', 'lib.python2.7.site-packages.pip.compat',
              'lib.python2.7.site-packages.pip.models', 'lib.python2.7.site-packages.pip._vendor',
              'lib.python2.7.site-packages.pip._vendor.distlib',
              'lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'lib.python2.7.site-packages.pip._vendor.colorama', 'lib.python2.7.site-packages.pip._vendor.html5lib',
              'lib.python2.7.site-packages.pip._vendor.html5lib.trie',
              'lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'lib.python2.7.site-packages.pip._vendor.html5lib.serializer',
              'lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'lib.python2.7.site-packages.pip._vendor.lockfile', 'lib.python2.7.site-packages.pip._vendor.progress',
              'lib.python2.7.site-packages.pip._vendor.requests',
              'lib.python2.7.site-packages.pip._vendor.requests.packages',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'lib.python2.7.site-packages.pip._vendor.packaging', 'lib.python2.7.site-packages.pip._vendor._markerlib',
              'lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'lib.python2.7.site-packages.pip._vendor.pkg_resources', 'lib.python2.7.site-packages.pip.commands',
              'lib.python2.7.site-packages.pip.operations', 'lib.python2.7.site-packages.click',
              'lib.python2.7.site-packages.flask', 'lib.python2.7.site-packages.flask.ext',
              'lib.python2.7.site-packages.pygal', 'lib.python2.7.site-packages.pygal.maps',
              'lib.python2.7.site-packages.pygal.test', 'lib.python2.7.site-packages.pygal.graph',
              'lib.python2.7.site-packages.wheel', 'lib.python2.7.site-packages.wheel.test',
              'lib.python2.7.site-packages.wheel.test.simple.dist.simpledist',
              'lib.python2.7.site-packages.wheel.test.complex-dist.complexdist',
              'lib.python2.7.site-packages.wheel.tool', 'lib.python2.7.site-packages.wheel.signatures',
              'lib.python2.7.site-packages.jinja2', 'lib.python2.7.site-packages.requests',
              'lib.python2.7.site-packages.requests.packages', 'lib.python2.7.site-packages.requests.packages.idna',
              'lib.python2.7.site-packages.requests.packages.chardet',
              'lib.python2.7.site-packages.requests.packages.urllib3',
              'lib.python2.7.site-packages.requests.packages.urllib3.util',
              'lib.python2.7.site-packages.requests.packages.urllib3.contrib',
              'lib.python2.7.site-packages.requests.packages.urllib3.packages',
              'lib.python2.7.site-packages.requests.packages.urllib3.packages.backports',
              'lib.python2.7.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'lib.python2.7.site-packages.werkzeug', 'lib.python2.7.site-packages.werkzeug.debug',
              'lib.python2.7.site-packages.werkzeug.contrib', 'lib.python2.7.site-packages._markerlib',
              'lib.python2.7.site-packages.markupsafe', 'lib.python2.7.site-packages.setuptools',
              'lib.python2.7.site-packages.setuptools.command', 'lib.python2.7.site-packages.pkg_resources',
              'lib.python2.7.site-packages.pkg_resources._vendor',
              'lib.python2.7.site-packages.pkg_resources._vendor.packaging', 'SafeNetworkingProject',
              'SafeNetworkingProject.lib.python2.7.distutils', 'SafeNetworkingProject.lib.python2.7.encodings',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip.req',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip.vcs',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip.utils',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip.compat',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip.models',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.distlib',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.colorama',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.html5lib',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.html5lib.trie',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.html5lib.serializer',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.lockfile',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.progress',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.requests',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.requests.packages',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.packaging',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor._markerlib',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip.commands',
              'SafeNetworkingProject.lib.python2.7.site-packages.pip.operations',
              'SafeNetworkingProject.lib.python2.7.site-packages.click',
              'SafeNetworkingProject.lib.python2.7.site-packages.flask',
              'SafeNetworkingProject.lib.python2.7.site-packages.flask.ext',
              'SafeNetworkingProject.lib.python2.7.site-packages.pygal',
              'SafeNetworkingProject.lib.python2.7.site-packages.pygal.maps',
              'SafeNetworkingProject.lib.python2.7.site-packages.pygal.test',
              'SafeNetworkingProject.lib.python2.7.site-packages.pygal.graph',
              'SafeNetworkingProject.lib.python2.7.site-packages.wheel',
              'SafeNetworkingProject.lib.python2.7.site-packages.wheel.test',
              'SafeNetworkingProject.lib.python2.7.site-packages.wheel.test.simple.dist.simpledist',
              'SafeNetworkingProject.lib.python2.7.site-packages.wheel.test.complex-dist.complexdist',
              'SafeNetworkingProject.lib.python2.7.site-packages.wheel.tool',
              'SafeNetworkingProject.lib.python2.7.site-packages.wheel.signatures',
              'SafeNetworkingProject.lib.python2.7.site-packages.jinja2',
              'SafeNetworkingProject.lib.python2.7.site-packages.requests',
              'SafeNetworkingProject.lib.python2.7.site-packages.requests.packages',
              'SafeNetworkingProject.lib.python2.7.site-packages.requests.packages.idna',
              'SafeNetworkingProject.lib.python2.7.site-packages.requests.packages.chardet',
              'SafeNetworkingProject.lib.python2.7.site-packages.requests.packages.urllib3',
              'SafeNetworkingProject.lib.python2.7.site-packages.requests.packages.urllib3.util',
              'SafeNetworkingProject.lib.python2.7.site-packages.requests.packages.urllib3.contrib',
              'SafeNetworkingProject.lib.python2.7.site-packages.requests.packages.urllib3.packages',
              'SafeNetworkingProject.lib.python2.7.site-packages.requests.packages.urllib3.packages.backports',
              'SafeNetworkingProject.lib.python2.7.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'SafeNetworkingProject.lib.python2.7.site-packages.werkzeug',
              'SafeNetworkingProject.lib.python2.7.site-packages.werkzeug.debug',
              'SafeNetworkingProject.lib.python2.7.site-packages.werkzeug.contrib',
              'SafeNetworkingProject.lib.python2.7.site-packages._markerlib',
              'SafeNetworkingProject.lib.python2.7.site-packages.markupsafe',
              'SafeNetworkingProject.lib.python2.7.site-packages.setuptools',
              'SafeNetworkingProject.lib.python2.7.site-packages.setuptools.command',
              'SafeNetworkingProject.lib.python2.7.site-packages.pkg_resources',
              'SafeNetworkingProject.lib.python2.7.site-packages.pkg_resources._vendor',
              'SafeNetworkingProject.lib.python2.7.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='Palo Alto Networks',
    author='Michael Clark',
    author_email='miclark@paloaltonetworks.com',
    description='Safe Networking'
)
